version: '3.9'

services:
  postgres:
    container_name: questydb
    image: postgres:latest
    restart: always
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - questy
  server:
    build: ./server
    ports:
      - '3000:3000'
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    networks:
      - questy

  client:
    build: ./client
    ports:
      - '4000:4000'
    depends_on:
      - server
    networks:
      - questy

volumes:
  postgres_data:

networks:
  questy:
